# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='index_number',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='year',
            field=models.IntegerField(choices=[(0, 'undefined'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0),
        ),
    ]
