# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signs', '0003_auto_20170301_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='group',
            field=models.IntegerField(max_length=2, null=True),
        ),
    ]
