# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 11:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signs', '0004_subject_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='group',
        ),
    ]
