# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-02 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signs', '0005_remove_subject_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_taken_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
