# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-02 13:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signs', '0006_subject_is_taken_by_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='is_taken_by_user',
        ),
    ]
