# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-10 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signs', '0009_auto_20170306_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='actual_space',
            field=models.IntegerField(default=0),
        ),
    ]
