# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-10 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signs', '0010_subject_actual_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_clicked',
            field=models.BooleanField(default=False),
        ),
    ]
